dist: xenial
os: linux

addons:
    apt_packages:
        - lib32z1
        - lib32stdc++6

language: c

env:
  global:
    - SOURCES=$TRAVIS_BUILD_DIR/src
    - SOURCES_SM=$TRAVIS_BUILD_DIR/addons/sourcemod/scripting
    - INCLUDES=$TRAVIS_BUILD_DIR/include
    - SOURCES_RIP=$TRAVIS_BUILD_DIR/ripext
    - SOURCES_JANSSON=$TRAVIS_BUILD_DIR/jansson
  jobs:
    - SMVERSION=1.10

install:
    - wget --input-file=http://sourcemod.net/smdrop/$SMVERSION/sourcemod-latest-linux
    - tar -xzf $(cat sourcemod-latest-linux)
    - git clone -b main https://github.com/nyood/sm-jansson.git $SOURCES_JANSSON
    - git clone -b main https://github.com/ErikMinekus/sm-ripext.git $SOURCES_RIP
before_script:
    - cp -R -f $INCLUDES $SOURCES_SM
    - cp -R -f $SOURCES_RIP/pawn/scripting/include $SOURCES_SM
    - cp -R -f $SOURCES_JANSSON/pawn/scripting/include $SOURCES_SM
    - chmod +x $SOURCES_SM/spcomp
    - chmod +x $TRAVIS_BUILD_DIR/travis/compile.sh
    - chmod +x $TRAVIS_BUILD_DIR/travis/package.sh
script:
    - bash ./travis/compile.sh $SOURCES $SOURCES_SM || exit 1

before_deploy:
    - bash ./travis/package.sh $SOURCES ${TRAVIS_BUILD_NUMBER} || exit 1

deploy:
  provider: releases
  token:
    secure: Psj4P1giX7Un/R7TPsPdMkuDiHTcVWTgCuQfVWMe1nFrLqeC0Uc59CpvhRaRs/+DpL6j8WHDWLhKpoX7c0UDWgaKy9FAGs0iXROXHKaJ20YrWomeaWBZNFseNcfOmiSmLzxVZ92sQJxwgzjaH5fjhc+I4kXoxKyf166yxyZzVVroZ+WNUNaOxcX+azz3i7XMAXD+57VF9Cc7mZs/z2mNF8HoQPKIN1QQ0QcVNqRMtJ0ZoUn+sKHQecGxtNirl0lc4RC4HRWt0ojSchszOVEzfHgvvnN82t1F86jFz8/YiHwDTyaYhjL6CLNX/f1yil2u3syhib6U/sKjnyLL4vkKrvk+8zpMDdu/1LUc3PkzX5xp/WzcTWzK5dMQTqTliiJVwCyfZa2Q/jtUVJULp7Moir3uZJN+8hJuqVtjRMBsZSw2iU2tw3Bn6DWPPQgQVUfd0ixGj8Dx9bSV0whiRSnCaxxjq9e1QI4ONro3sWpUE1pmN6JF41tfzCCX2gRr6aGKd9pJiw8pLwPRD0u6HEasX7lxeBf7nsjJWXABeZVYr1O1vyOTriQ1fvkVStg1feDAIb9LtgV5rMLmpM5u3OWTSGUS9/W2elrZX1EPkUvcQ6jpOf6M1J/MK0dzAi2gzwY1B3XI3zGJgq87kU+c6h8xf/kclB/boO/6r1ZOcn2QoCA=
  file_glob: true
  file: $SOURCES/*
  skip_cleanup: true
  on:
    tags: true
  
notifications:
    email: false
